imports:
    - { resource: default_parameters.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: env/platformsh.php }

# Configuration for Database connection, can have several connections used by eZ Repositories in ezplatform.yml
doctrine:
    dbal:
        connections:
            default:
                driver: '%env(DATABASE_DRIVER)%'
                host: '%env(DATABASE_HOST)%'
                port: '%env(DATABASE_PORT)%'
                user: '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PASSWORD)%'
                dbname: '%env(DATABASE_NAME)%'
                charset: UTF8

# Base configuration for Solr, for more options see: https://doc.ez.no/display/EZP/Solr+Search+Engine+Bundle
# Can have several connections used by each eZ Repositories in ezplatform.yml
ez_search_engine_solr:
    endpoints:
        endpoint0:
            dsn: '%env(SOLR_DSN)%'
            core: collection1
    connections:
        default:
            entry_endpoints:
                - endpoint0
            mapping:
                default: endpoint0

framework:
    esi:             ~
    translator:      { fallback: "%locale_fallback%" }
    secret:          '%env(SYMFONY_SECRET)%'
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    csrf_protection: ~
    form:            ~
    validation:      { enable_annotations: true }
    # Place "eztpl" engine first intentionnally.
    # This is to avoid template name parsing with Twig engine, refusing specific characters
    # which are valid with legacy tpl files.
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale_fallback%"
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
#        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
        save_path:   "/var/lib/php/sessions"
        # Note: eZ Publish also allows session name and session cookie configuration to be per SiteAccess, by
        #       default session name will be set to "eZSESSID{siteaccess_hash}" (unique session name per siteaccess)
        #       Further reading on sessions: https://doc.ez.no/display/DEVELOPER/Sessions
    fragments:       ~
    http_method_override: true
    assets: true
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: "%kernel.debug%"
    bundles:        [ eZStudioDemoBundle, EzSystemsPersonalizedBlockBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        bootstrap_glyphicons_eot:
            inputs:
                - "%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.eot"
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - "%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.svg"
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_ttf:
            inputs:
                - "%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.ttf"
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_woff:
            inputs:
                - "%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.woff"
            output: "fonts/glyphicons-halflings-regular.woff"
        bootstrap_glyphicons_woff2:
            inputs:
                - "%kernel.root_dir%/../vendor/components/bootstrap/fonts/glyphicons-halflings-regular.woff2"
            output: "fonts/glyphicons-halflings-regular.woff2"
        demo_css:
            inputs:
            - '%kernel.root_dir%/../vendor/components/bootstrap/css/bootstrap.min.css'
            - 'bundles/ezstudiodemo/css/studiodemo.css'
            - 'bundles/ezstudiodemo/css/responsive.css'
            - 'bundles/ezstudiodemo/css/user_forms.css'
            - 'bundles/ezstudiodemo/css/content_types/subscribe.css'
            - 'bundles/ezstudiodemo/css/content_types/about.css'
            - 'bundles/ezstudiodemo/css/content_types/blog.css'
            - 'bundles/ezstudiodemo/css/content_types/blog_post.css'
            - 'bundles/ezstudiodemo/css/content_types/place.css'
            - 'bundles/ezstudiodemo/css/content_types/article.css'
            - 'bundles/ezstudiodemo/css/content_types/place_list.css'
            - 'bundles/ezstudiodemo/css/content_types/product_list.css'
            - 'bundles/ezstudiodemo/css/content_types/folder.css'
            - 'bundles/ezstudiodemo/css/content_types/product.css'
            - 'bundles/ezstudiodemo/css/blocks/contentlist.css'
            - 'bundles/ezstudiodemo/css/blocks/rss.css'
            - 'bundles/ezstudiodemo/css/blocks/banner.css'
            - 'bundles/ezstudiodemo/css/blocks/gallery.css'
            - 'bundles/ezstudiodemo/css/blocks/embed.css'
            - 'bundles/ezstudiodemo/css/blocks/keyword.css'
            - 'bundles/ezstudiodemo/css/blocks/embed.css'
            - 'bundles/ezstudiodemo/css/blocks/keyword.css'
            - 'bundles/ezstudiodemo/css/personalized.css'
            - 'bundles/ezsystemsformbuilder/css/vendors/*/*.css'
        demo_js:
            inputs:
                - '%kernel.root_dir%/../vendor/components/jquery/jquery.min.js'
                - '%kernel.root_dir%/../vendor/components/bootstrap/js/bootstrap.min.js'
                - '%kernel.root_dir%/../vendor/components/handlebars.js/handlebars.min.js'
                - 'bundles/ezsystemsrecommendation/js/*'
                - 'bundles/ezsystemspersonalizedblock/js/*'
                - 'bundles/ezsystemsformbuilder/js/vendors/*/*.js'
        admin_css:
            inputs:
                - '$css.files;ez_platformui$'
        admin_js:
            inputs:
                - '$javascript.files;ez_platformui$'
                - 'bundles/bazingajstranslation/js/translator.min.js'
                - 'bundles/ezplatformuiassets/vendors/yui3/build/yui/yui-min.js'
                - 'bundles/ezplatformuiassets/vendors/handlebars-helper-intl/dist/handlebars-intl.min.js'

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      '%env(MAILER_HOST)%'
    username:  '%env(MAILER_USER)%'
    password:  '%env(MAILER_PASSWORD)%'
    spool:     { type: memory }
